### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by undergroundSimplex** [alexmurray/tpm2-tools-snap#2]
Some commands are missing, could you please also add following commands to the package please?

- tpm2_flushcontext
- tpm2_duplicate
- tpm2_rc_decode
- tpm2_testparms

**Comment by alexmurray** [comment]
Thanks for reporting this - I can't see tpm2_testparams in the 4.3.0 release anywhere but I've added the other 3 now. This will rebuild soon and should be available on the edge channel within ~ half-an-hour with any luck.
